name: NPM release
on:
  release:
    types: [published]

jobs:
  build:
    uses: ./.github/workflows/template-build.yml

  publish-core:
    name: "Publish `core` package"
    needs:
      - build

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v7
        with:
          name: byloth-vuert

      - name: Configuring Node.js 24 (LTS)
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/

      - name: Updating npm to the latest version
        run: npm install -g npm@latest
      - if: ${{ github.event.release.prerelease == true }}
        name: Publishing pre-release package
        run: npm publish --access public --tag next
      - if: ${{ github.event.release.prerelease == false }}
        name: Publishing latest package
        run: npm publish --access public

  publish-nuxt:
    name: "Publish `nuxt` package"
    needs:
      - build

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Downloading the artifact
        uses: actions/download-artifact@v7
        with:
          name: byloth-nuxt-vuert-module

      - name: Configuring Node.js 24 (LTS)
        uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://npm.pkg.github.com/

      - name: Updating npm to the latest version
        run: npm install -g npm@latest
      - if: ${{ github.event.release.prerelease == true }}
        name: Publishing pre-release package
        run: npm publish --access public --tag next
      - if: ${{ github.event.release.prerelease == false }}
        name: Publishing latest package
        run: npm publish --access public
